// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzK4b0fnNV4-Qe-BbeNy1g2e4-M7OgAF4',
    appId: '1:38061758612:web:cc1e9b31fb3d6681dd3c81',
    messagingSenderId: '38061758612',
    projectId: 'tidy-life-project333',
    authDomain: 'tidy-life-project333.firebaseapp.com',
    storageBucket: 'tidy-life-project333.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5Wn989etny9o-yq9gMoRvL0agiQteL4',
    appId: '1:38061758612:android:e9ca8b54c233f7f8dd3c81',
    messagingSenderId: '38061758612',
    projectId: 'tidy-life-project333',
    storageBucket: 'tidy-life-project333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ7v46ajp-7m5sms9-HDhQFpo3TPSo7Vg',
    appId: '1:38061758612:ios:2103a997931250aadd3c81',
    messagingSenderId: '38061758612',
    projectId: 'tidy-life-project333',
    storageBucket: 'tidy-life-project333.appspot.com',
    iosClientId: '38061758612-vkpkdn03mqatm0scv4ummshphdr40sbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tidyLife1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ7v46ajp-7m5sms9-HDhQFpo3TPSo7Vg',
    appId: '1:38061758612:ios:2103a997931250aadd3c81',
    messagingSenderId: '38061758612',
    projectId: 'tidy-life-project333',
    storageBucket: 'tidy-life-project333.appspot.com',
    iosClientId: '38061758612-vkpkdn03mqatm0scv4ummshphdr40sbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.tidyLife1',
  );
}
